name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'        
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: linux package
      uses: actions/upload-artifact@v2.2.4
      with:
        name: yatt-pipe-linux
        path: dist/yatt-pipe-linux
    - name: mac package
      uses: actions/upload-artifact@v2.2.4
      with:
        name: yatt-pipe-macos
        path: dist/yatt-pipe-macos     
    - name: win package
      uses: actions/upload-artifact@v2.2.4
      with:
        name: yatt-pipe-win
        path: dist/yatt-pipe-win.exe        