name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: linux package
        uses: actions/upload-artifact@v2.2.4
        with:
          name: yatt-demo-device-linux
          path: dist/yatt-demo-device-linux
      - name: mac package
        uses: actions/upload-artifact@v2.2.4
        with:
          name: yatt-demo-device-macos
          path: dist/yatt-demo-device-macos     
      - name: win package
        uses: actions/upload-artifact@v2.2.4
        with:
          name: yatt-demo-device-win
          path: dist/yatt-demo-device-win.exe          